Marketpricetable task2 - 페이지네이션 구현
codeit-bootcamp-frontend/0-crypto-meter-techno-leaders pull request #10
Opened 2023-05-17 14:01 UTC by redcoin96

**작업사항**
- 커스텀 페이지네이션 스타일 적용
- api 페이지네이션 구현
- 원화<=>달러 변경 로직 구현(임시)

2023-05-17 14:18 UTC, Andy-Shin99 commented on src/components/MarketPriceTable_api.jsx
> +  };
try...catch 문의 활용이 너무 훌륭합니다 👍

2023-05-17 14:20 UTC, Andy-Shin99 commented
내일 오전 중으로 코드리뷰를 추가로 해보겠습니다. 너무 고생하셨습니다.
변동 % 를 보여주는 column들에서는 % 기호가 숫자 뒤에 추가되어야 할 것 같아요!

2023-05-18 01:50 UTC, Andy-Shin99 commented on src/components/MarketPriceTable_api.jsx
>    const columns = [
coin-name-container 내 img src가 없을 때는 기본 이미지를 보여주는 것으로 변경하면 좋을 것 같습니다.

2023-05-18 01:53 UTC, Andy-Shin99 approved these changes

2023-05-18 04:08 UTC, hayoung-99 approved these changes

2023-05-18 12:55 UTC, 09sally requested changes

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +function getPriceChangePercentageDiv(value) {
1. 컴포넌트의 경우 앞글자를 꼭 대문자로 해주세용!
2. 그리고 PriceChangePercentage로 이름을 변경하면 좋을 것 같습니다!
3. jsx 문법을 쓰는 컴포넌트의 경우 파라미터가 props이거나 구조분해 해서 쓰면 좋을 것 같습니다!
```
function PriceChangePercentage( { value } ) 
```

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +  const priceChangePercentage = value !== null ? value.toFixed(2) : '-';
삼항 연산자를 이렇게 써 보면 어떨까요?
```
const priceChangePercentage = value ? `${Math.round(value, 2)}%`  : '-';

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +        <span>{priceChangePercentage}</span>
61~64번 줄을 이렇게 하면 될 것 같아요!
```
<span>{priceChangePercentage}</span>
```

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +    value !== null ? (value < 0 ? 'negative' : 'positive') : '';
더불어서 이렇게 해보면 어떨까요?

내일 다시 작성해볼게요

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +      }));
저도 동의합니다 화이팅!
handleLoad

2023-05-18 12:55 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +  };
수정이 필요할 것 같은데 금~토 중으로 context 작업해야 확정될 것 같아요!

2023-05-18 13:00 UTC, 09sally commented
Closes #12

2023-05-20 16:39 UTC, merged