Gnb task4 - HistoryList, HistoryItem 구현
codeit-bootcamp-frontend/0-crypto-meter-techno-leaders pull request #11
Opened 2023-05-18 11:32 UTC by Andy-Shin99

## 구현 사항
검색 기록 모달 안에 HistoryList를 wrapper로 생성하고, 그 내부에 하나하나의 기록을 Item 형식으로 배치하려고 합니다.
```
HistoryModal
├─ div
│  ├─ heading
│  └─ Button
└─ HistoryList
   ├─ HistoryItem
   ├─ HistoryItem
   └─ ....
```

와 같은 구조를 가지게 될 예정입니다.
이 때 Item에 들어갈 data는 로컬 스토리지에 배열 형식으로 저장되어 있는 검색기록을 가져와 HistoryItem를 하나씩 생성하며 넣어주려고 합니다.

----

data는 mock data(비트코인 data 및 임의 날짜)로 하나 넣어보았고 잘 출력이 되는 것을 확인하였습니다.
아마 로컬스토리지에서 받아온 데이터를 가공해서 HistoryItem에 현재 들어있는 prop 형태로 내려주지 않을까 싶습니다.

2023-05-18 11:34 UTC, Andy-Shin99 commented on src/components/GNB/HistoryItem.jsx
> +    currentValue,
임의로 변수명들을 설정해 보았습니다.
나은 의견있으시면 말씀해 주세요 😉

2023-05-18 11:40 UTC, Andy-Shin99 commented on src/components/GNB/HistoryItem.jsx
> +            {coinName} 코인을 샀다면, {currentDate}에는 {currentValue}원입니다.
pigma를 보니 {currenValue}의 글자 디자인이 달라 span 태그로 감싸주어야 할 것 같습니다.
수정해 두겠습니다.

추가로, 아마 티나가 활용하시는 상승, 하락시 색상변화를 저도 사용해야 할 것 같은데 혹시 티나는 상승 하락을 어떤 방식으로 계산을 하시는지, 계산하는 함수가 따로 있으신지 궁금합니다. 만약 따로 사용하시는 함수가 없으면 저는 받아오는 데이터로 (currenValue - investment) 계산을 해주고, 결과값이 양수인지 음수인지 0인지에 따라 색상을 달리 해주려고 합니다.

2023-05-18 11:41 UTC, Andy-Shin99 commented on src/components/GNB/HistoryModal.jsx
> +const dateString = (years, months, days) => {
지금 당장 date formatting이 필요해 만들어 둔 함수입니다.
아마 앨리스나 샐리가 만들어 둔 date formatting 함수가 있을 것 같아서 그거 가져다 사용할 예정입니다.
모듈화 부탁드려용~

2023-05-18 11:41 UTC, Andy-Shin99 commented on src/components/GNB/HistoryModal.jsx
> +const datas = {
임의로 지정한 mock-data입니다

2023-05-18 11:42 UTC, Andy-Shin99 commented on src/components/GNB/HistoryModal.jsx
>    overlay: {
content-box 외부를 클릭하면 모달이 꺼질 수 있도록 만들어 주었습니다.
이제 GNB 부분을 클릭하여도 모달이 잘 꺼지게 되었습니다.

2023-05-18 12:36 UTC, hayoung-99 approved these changes

2023-05-18 12:36 UTC, hayoung-99 commented on src/components/GNB/HistoryModal.jsx
> +import HistoryItem from './HistoryItem';
절대경로 부탁드립니다👍

2023-05-18 12:36 UTC, hayoung-99 commented on src/components/GNB/HistoryModal.jsx
> +  const month = newDate.getMonth();
이 부분은 따로 모듈화를 하겠지만 getMonth는 1월이 0부터 시작해서 +1 해서 테스트하면 좋을 것 같습니당

2023-05-18 12:39 UTC, hayoung-99 commented on src/components/GNB/HistoryModal.jsx
> +  const month = newDate.getMonth();
그리고 제 쪽(시세 차트)에서 쓰는 format 함수는 시간 데이터를 한 개만 받아서 쓰고 있는데, 
흠.. 모듈화를 하려면 파라미터 개수를 통일시켜야 해서 이건 의논을 해봐야될 것 같습니다!
일단 저는 milliseconds 하나를 받아서 dateformat을 하고 있습니다.

2023-05-19 08:04 UTC, 09sally requested changes
HistoryList와 HistoryListItem의 기능과 책임을 좀 더 구체화해서 나누면 좋을 것 같습니다.
현재 Modal 컴포넌트는 모달창 열고 닫는 기능과 HistoryList의 정보들을 보여주는 기능,
그리고 HistoryList는 Localstorage에서 저장된 정보들을 불러오는 기능을 할 것 같은데

HistoryList의 return값에 HistoryListItem을 렌더링하는 것이 좀 더 좋은 방법이라는 생각이 듭니다!
이후에 Modal 컴포넌트에는 HistoryList만 렌더링하면 되겠죠?

2023-05-19 08:04 UTC, 09sally commented on src/components/GNB/HistoryList.jsx
> +
HistoryList 컴포넌트의 기능이 딱히 없는 것 같습니다.
ul 태그로 감싸주는 역할만 해서 모달 컴포넌트에서 ul 태그를 쓰면 될 것 같습니다!

아니면 ul 태그 안에 HistoryItem을 렌더링하고 모달에서 HistoryList만 렌더링하는 방법도 있겠네요

2023-05-19 08:04 UTC, 09sally commented on src/components/GNB/HistoryModal.jsx
> +        <HistoryItem datas={datas} />
위에서도 한 번 말씀드렸듯이
HistoryList 컴포넌트의 기능이 딱히 없는 것 같습니다.
ul 태그로 감싸주는 역할만 해서 모달 컴포넌트에서 ul 태그를 쓰면 될 것 같습니다!

2023-05-19 08:04 UTC, 09sally commented on src/components/GNB/HistoryItem.jsx
> +function HistoryItem({ datas }) {
HistoryListItem이라고 하면 더 좋을 것 같습니다!

2023-05-19 08:04 UTC, 09sally requested changes
HistoryList와 HistoryListItem의 기능과 책임을 좀 더 구체화해서 나누면 좋을 것 같습니다.
현재 Modal 컴포넌트는 모달창 열고 닫는 기능과 HistoryList의 정보들을 보여주는 기능,
그리고 HistoryList는 Localstorage에서 저장된 정보들을 불러오는 기능을 할 것 같은데

HistoryList의 return값에 HistoryListItem을 렌더링하는 것이 좀 더 좋은 방법이라는 생각이 듭니다!
이후에 Modal 컴포넌트에는 HistoryList만 렌더링하면 되겠죠?

2023-05-19 08:05 UTC, 09sally commented
HistoryList와 HistoryListItem의 기능과 책임을 좀 더 구체화해서 나누면 좋을 것 같습니다.
현재 Modal 컴포넌트는 모달창 열고 닫는 기능과 HistoryList의 정보들을 보여주는 기능,
그리고 HistoryList는 Localstorage에서 저장된 정보들을 불러오는 기능을 할 것 같은데

HistoryList의 return값에 HistoryListItem을 렌더링하는 것이 좀 더 좋은 방법이라는 생각이 듭니다!
이후에 Modal 컴포넌트에는 HistoryList만 렌더링하면 되겠죠?

2023-05-19 08:47 UTC, merged