MarketPriceTable-task1: 컴포넌트 구조 만들기
codeit-bootcamp-frontend/0-crypto-meter-techno-leaders pull request #5
Opened 2023-05-15 07:00 UTC by redcoin96

## 적용화면
![scrnli_2023- 5- 15- 오후 12-07-44](https://github.com/codeit-bootcamp-frontend/0-crypto-meter-techno-leaders/assets/129242822/5bfb8496-080d-48bd-a403-bfb9113951f9)

## MarketPriceTable
```
└─ components
   ├─ MarketPriceTable.api
   └─ MarketPriceTable.mock
   ```
- **MarketPriceTable.api:** api를 사용하여 구현한 컴포넌트(페이지네이션 x)
- **MarketPriceTable.mock**: mock.json을 사용하여 구현한 컴포넌트
- 컴포넌트 구성에 대한 구체적인 부분은 셀프 코드리뷰를 통해 남기겠습니다!

## Progress
- [x] mock데이터 적용 
- [x] 폰트 등 스타일 적용
- [x] 정렬 기능
- [x] 데이터 포맷팅
- [ ] 페이지네이션 버튼 여러 페이지로 적용
![scrnli_2023- 5- 15- 오후 3-57-45](https://github.com/codeit-bootcamp-frontend/0-crypto-meter-techno-leaders/assets/129242822/3180a36f-dfa8-4d15-94ff-947e9e9b64b1)

## Issue
- MarketPriceTable.api부분에서 쿼리스트링을 사용하여 임의로 만들어놓은 통화버튼 클릭시 서로 다른통화의 데이터를 불러 오는 방식으로 구현했으나 20번 정도의 요청이 지나면 서버에서 429에러 발생

## Suggestion
- 통화 변경 버튼을 누를때마다 쿼리스트링으로 api요청을 하는 것이 아닌 다른 통화의 api를 처음에 한번에 받아온 후 데이터를 적용해야 할 것 같습니다.

2023-05-15 07:16 UTC, Andy-Shin99 commented on src/components/MarketPriceTable_api.jsx
> +  const combinedClassName = clsx('price-change-percentage', cellClassName);
clsx 사용할 때 조건에 따라 className을 [적용할 수 있는 방법](https://codiving.kr/85) 도 있는 것 같아요
```
const combinedClassName = clsx('price-change-precentage', {['negative']: value < 0, ['positive']: value > 0})
```

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +  );
통화변경이 될때마다 새로 api를 가져오는 로직으로 구현을 했는데, 서버 문제로 데이터를 받아온 후 적용하는 방식으로 수정해야 할 것 같습니다ㅠ

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +          }}
**DataGrid 컴포넌트 = 테이블의 표가 들어가있는 컴포넌트입니다.**
border가 컴포넌트의 기본 스타일로 들어가 있는 것 같아 우선은 인라인으로 스타일을 변경했습니다.

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +          }}
통화를 변경하는 버튼을 누르면 currenct state에 따라 통화가 변경되도록 임의로 추가했습니다.

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +    },
라이브러리를 살펴보니 column은 배열데이터를 받고, params를 객체로 받아 각 field에 해당하는 값을 데이터의 키값으로 받아 params.value로 받는 것 같습니다. 또한 renderCell로 콜백함수를 넘겨주면 렌더링을 해주는 형식이라고 생각해주시면 될 것 같습니다!
**ex) field로 id를 넘겨줄시 json 데이터의 id키의 값 = params.value값이 됨**

+field외에 전달해준 키값을 불러오고 싶을시에는 **params.row.객체키값** 으로 가져올 수 있습니다.

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +}
**'변동폭'에 들어가는 데이터를 렌더링해주는 함수입니다.**
column배열 내 변동폭 데이터에 renderCell의 값에 들어가는 로직이 중복되어 함수로 분리했습니다.
변동폭의 데이터를 받아 소수점 뒤 2번째 자리까지 표시해준 이후에 해당 값이 음수이면 negative, 양수이면 positive 클래스명을 추가하여 각 클래스에 따라 색상등이 다르게 렌더링되도록 처리해주었습니다.

* **clsx** : 여러개의 classname을 combine해주는 라이브러리입니다. 위에서는 'price-change-percentage' 클래스에 변동폭 데이터의 틀을 잡아주고 cellClassName을 같이 추가하여 negative와 positive에 따라 다른 색상으로 렌더링해주도록 구현했습니다.
'

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +          id: index + 1,
api 데이터에서는 id값이 코인이름으로 되어있어 아이디 값을 인덱스+1로 재설정해주었습니다.

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +  };
**formattedCoinTotalVolume**: 24시간 거래량 column에 원화를 코인으로 변환한 부분을 렌더링해주는 함수입니다.

2023-05-15 07:47 UTC, redcoin96 commented on src/components/MarketPriceTable_mock.jsx
> +    return `￦${value.toLocaleString()}`;
MarketPriceTable_api.jsx 파일과 크게 다른점은 없고  통화는 우선 원화로 설정하였습니다.

2023-05-15 08:33 UTC, 09sally commented on package.json
> +    "@mui/x-data-grid-generator": "^6.4.0",
사용한 library 종류를 PR이나 프로젝트 노션에 기록해주시면 좋을 것 같아요!

2023-05-16 10:38 UTC, 09sally requested changes

2023-05-16 10:38 UTC, 09sally commented on src/components/MarketPriceTable_api.jsx
> +    cellClassName = 'positive';
3항 연산자를 써도 좋을 것 같아요!

2023-05-16 11:32 UTC, Andy-Shin99 approved these changes

2023-05-17 01:33 UTC, hayoung-99 approved these changes

2023-05-17 10:48 UTC, merged

2023-05-17 11:01 UTC, redcoin96 commented on src/components/MarketPriceTable_api.jsx
> +    cellClassName = 'positive';
아 이 부분을 제가 깜빡했네요.. 죄송합니다ㅠ 말씀주신대로 value가 0일 경우 때문에 이렇게 진행했었던 것 같아요